# Generated by Django 4.2.30 on 2026-05-12 15:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armoire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Armoire',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Rayon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('position', models.CharField(blank=True, help_text='Ex: R1, R2, Haut, Bas', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('armoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rayons', to='armoires.armoire')),
            ],
            options={
                'verbose_name': 'Rayon',
                'ordering': ['code'],
            },
        ),
    ]
