# Generated by Django 4.2.30 on 2026-05-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armoires', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rayon',
            name='position',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
