# Generated by Django 4.2.30 on 2026-06-15 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0003_alter_departement_options_and_more'),
        ('armoires', '0002_alter_rayon_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='armoire',
            options={'ordering': ['departement__nom', 'service__nom', 'code'], 'verbose_name': 'Armoire'},
        ),
        migrations.AddField(
            model_name='armoire',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='armoires', to='entreprise.departement'),
        ),
        migrations.AddField(
            model_name='armoire',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='armoires', to='entreprise.service'),
        ),
    ]
