# Generated by Django 4.2.30 on 2026-06-15 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0003_alter_departement_options_and_more'),
        ('armoires', '0003_alter_armoire_options_armoire_departement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='armoire',
            options={'ordering': ['service__departement__nom', 'service__nom', 'code'], 'verbose_name': 'Armoire'},
        ),
        migrations.RemoveField(
            model_name='armoire',
            name='departement',
        ),
        migrations.AlterField(
            model_name='armoire',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='armoires', to='entreprise.service'),
        ),
    ]
