# Generated by Django 4.2.30 on 2026-05-16 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaborateur',
            options={'ordering': ['nom', 'prenom'], 'verbose_name': 'Collaborateur'},
        ),
    ]
