# Generated by Django 4.2.30 on 2026-06-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_collaborateur_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborateur',
            name='is_principal',
            field=models.BooleanField(default=False),
        ),
    ]
