# Generated by Django 4.2.30 on 2026-05-13 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entreprise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleDepartementService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('droit', models.CharField(choices=[('LECTURE', 'Lecture seule'), ('ECRITURE', 'Lecture et écriture'), ('ADMIN', 'Administration complète')], default='LECTURE', max_length=20)),
                ('collaborateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_departement_service', to=settings.AUTH_USER_MODEL)),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='entreprise.departement')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='entreprise.service')),
            ],
            options={
                'verbose_name': 'Rôle Département/Service',
                'unique_together': {('collaborateur', 'departement', 'service')},
            },
        ),
    ]
