# Generated by Django 4.2.30 on 2026-05-16 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entreprise', '0002_roledepartementservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departement',
            options={'ordering': ['nom'], 'verbose_name': 'Departement'},
        ),
        migrations.AlterModelOptions(
            name='roledepartementservice',
            options={'verbose_name': 'Role Departement/Service'},
        ),
        migrations.AlterField(
            model_name='roledepartementservice',
            name='collaborateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_dept_service', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roledepartementservice',
            name='droit',
            field=models.CharField(choices=[('LECTURE', 'Lecture seule'), ('ECRITURE', 'Lecture et ecriture'), ('ADMIN', 'Administration complete')], default='LECTURE', max_length=20),
        ),
    ]
