# Generated by Django 4.2.30 on 2026-05-12 15:01

import apps.documents.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('armoires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_unique', models.CharField(editable=False, max_length=60, unique=True)),
                ('titre', models.CharField(max_length=255)),
                ('type_doc', models.CharField(max_length=100)),
                ('date_creation', models.DateField(help_text='Date du document original')),
                ('date_numerisation', models.DateTimeField(auto_now_add=True)),
                ('fichier', models.FileField(upload_to=apps.documents.models.document_upload_path)),
                ('nom_fichier', models.CharField(editable=False, max_length=255)),
                ('taille', models.BigIntegerField(default=0, editable=False)),
                ('chemin_stockage', models.CharField(editable=False, max_length=500)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('ARCHIVE', 'Archivé'), ('SUPPRIME', 'Supprimé')], default='ACTIF', max_length=20)),
                ('createur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_crees', to=settings.AUTH_USER_MODEL)),
                ('rayon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='armoires.rayon')),
            ],
            options={
                'verbose_name': 'Document',
                'ordering': ['-date_numerisation'],
            },
        ),
        migrations.CreateModel(
            name='MetadataDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auteur', models.CharField(blank=True, max_length=200)),
                ('date_emission', models.DateField(blank=True, null=True)),
                ('mots_cles', models.JSONField(blank=True, default=list)),
                ('destinataire', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='documents.document')),
            ],
            options={
                'verbose_name': 'Métadonnée',
            },
        ),
    ]
