# Generated by Django 4.2.30 on 2026-05-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metadatadocument',
            options={'verbose_name': 'Metadonnee'},
        ),
        migrations.AlterField(
            model_name='document',
            name='chemin_stockage',
            field=models.CharField(blank=True, editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='code_unique',
            field=models.CharField(editable=False, max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='nom_fichier',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='statut',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('ARCHIVE', 'Archive'), ('SUPPRIME', 'Supprime')], default='ACTIF', max_length=20),
        ),
    ]
