# Generated by Django 4.2.30 on 2026-06-01 09:34

import apps.documents.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0002_alter_metadatadocument_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadatadocument',
            name='texte_extrait',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_version', models.IntegerField(default=1)),
                ('fichier', models.FileField(upload_to=apps.documents.models.document_upload_path)),
                ('nom_fichier', models.CharField(max_length=255)),
                ('taille', models.BigIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('createur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions_crees', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
            ],
            options={
                'verbose_name': 'Version de Document',
                'ordering': ['-numero_version'],
            },
        ),
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cle_securite', models.CharField(blank=True, help_text='Mot de passe hashe', max_length=128, null=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('nombre_telechargements', models.IntegerField(default=0)),
                ('telechargements_max', models.IntegerField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partages_crees', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partages', to='documents.document')),
            ],
            options={
                'verbose_name': 'Partage de Document',
                'ordering': ['-date_creation'],
            },
        ),
    ]
