# Generated by Django 4.2.30 on 2026-06-04 16:08

import apps.documents.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0003_metadatadocument_texte_extrait_documentversion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_version', models.PositiveIntegerField()),
                ('fichier', models.FileField(upload_to=apps.documents.models.version_upload_path)),
                ('nom_fichier', models.CharField(blank=True, max_length=255)),
                ('taille', models.BigIntegerField(default=0)),
                ('commentaire', models.TextField(blank=True, help_text='Motif ou description de la modification')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_courante', models.BooleanField(default=False)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions_creees', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
            ],
            options={
                'verbose_name': 'Version de document',
                'ordering': ['-numero_version'],
                'unique_together': {('document', 'numero_version')},
            },
        ),
        migrations.RemoveField(
            model_name='documentversion',
            name='createur',
        ),
        migrations.RemoveField(
            model_name='documentversion',
            name='document',
        ),
        migrations.RemoveField(
            model_name='metadatadocument',
            name='texte_extrait',
        ),
        migrations.DeleteModel(
            name='DocumentShare',
        ),
        migrations.DeleteModel(
            name='DocumentVersion',
        ),
    ]
