# Generated by Django 4.2.30 on 2026-06-08 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0004_versiondocument_remove_documentversion_createur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadatadocument',
            name='texte_extrait',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cle_securite', models.CharField(blank=True, help_text='Mot de passe hashe', max_length=128, null=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('nombre_telechargements', models.IntegerField(default=0)),
                ('telechargements_max', models.IntegerField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partages_crees', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partages', to='documents.document')),
            ],
            options={
                'verbose_name': 'Partage de Document',
                'ordering': ['-date_creation'],
            },
        ),
    ]
