# Generated by Django 4.2.30 on 2026-05-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalaction',
            name='type_action',
            field=models.CharField(choices=[('CREATION', 'Creation'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression'), ('CONSULTATION', 'Consultation'), ('TELECHARGEMENT', 'Telechargement'), ('DEPLACEMENT', 'Deplacement'), ('CONNEXION', 'Connexion'), ('DECONNEXION', 'Deconnexion')], max_length=30),
        ),
    ]
